### ISSUE TITLE
BCL UVMLint

### ISSUE THREAD

**Issue by ak-vworks** [accellera-official/uvm-core#11]
Hi,
  As part of our development @AsFigo we developed a custom UVMLint for BCL and the results can be found at https://asfigo.blogspot.com/2024/03/customizing-uvmlint-for-ieee-18002-base.html 

Happy to share more details if anyone is interested.

Ajeetha
AsFigo

**Comment by mstrickland-mrvl** [comment]
Thanks for providing these results.  We will close this as "not a bug".

**Comment by jwayar** [comment]
> Hi, As part of our development [@AsFigo](https://github.com/AsFigo) we developed a custom UVMLint for BCL and the results can be found at https://asfigo.blogspot.com/2024/03/customizing-uvmlint-for-ieee-18002-base.html
> 
> Happy to share more details if anyone is interested.
> 
> Ajeetha AsFigo

Hi! I'am interested, how to abtain more details?
